# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 18:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motivo', models.CharField(max_length=150)),
                ('Fecha_anulacion', models.DateField()),
            ],
            options={
                'ordering': ['Fecha_anulacion'],
                'verbose_name_plural': 'Solicitudes anuladas',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_dpto', models.CharField(max_length=50)),
                ('Mision', models.CharField(blank=True, max_length=50)),
                ('Vision', models.CharField(blank=True, max_length=50)),
                ('Historia', models.CharField(blank=True, max_length=50)),
                ('Ubicacion', models.CharField(blank=True, max_length=50)),
                ('Organizacion', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Hora', models.TimeField(blank=True, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=200)),
                ('Daniado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Telefono', models.IntegerField(null=True)),
                ('Correo', models.EmailField(blank=True, max_length=100)),
                ('Informacion_adicional', models.CharField(blank=True, max_length=50)),
                ('Foto', models.ImageField(blank=True, upload_to=b'')),
                ('Activo', models.NullBooleanField()),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Carrera')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_proyector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marca de proyector',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_prestamo', models.DateField()),
                ('Hora', models.TimeField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['Fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('estado', models.NullBooleanField()),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Marca_proyector')),
            ],
            options={
                'verbose_name_plural': 'Proyectores',
            },
            managers=[
                ('Total', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abreviatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seccion', models.IntegerField(blank=True, null=True)),
                ('Fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('Hora_solicitud', models.TimeField()),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Asignatura')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Docente')),
                ('Estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SPP.Estado')),
                ('Proyector_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Proyector')),
            ],
            options={
                'ordering': ['Fecha_solicitud', 'Estado'],
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPP.Solicitud'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='Rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Rango'),
        ),
        migrations.AddField(
            model_name='docente',
            name='Especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPP.Especialidad'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='Solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPP.Solicitud'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='Solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPP.Solicitud'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
