# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anulacion',
            name='Solicitud',
        ),
        migrations.RemoveField(
            model_name='anulacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='Solicitud',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='Prestamo',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to='SPP.Prestamo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Anulacion',
        ),
    ]
