# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPP', '0002_auto_20170718_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='Proyector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SPP.Proyector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='Daniado',
            field=models.NullBooleanField(default=False),
        ),
    ]
